### ISSUE TITLE
zlib CCFLAGS

### ISSUE THREAD

**Issue by dooxe** [charmie11/CImg-hello-world#1]
Hello, 

First, I want to thank you for having shared your CImg-hello-world CMake, this is a great piece of work.

Then, I have just noticed that there is no CIMG_ZLIB_CCFLAGS set in your FindCImg.cmake. It could be interesting to set it to "-Dcimg_use_zlib" so one could save compressed CImg image format on the disk (.cimgz) for example.

**Comment by charmie11** [comment]
Thanks for your feedback!!

I updated FindCImg.cmake as you suggested and added a test function in main.cpp to use save_cimg() with zlib compression.
